[[language]]
name = "dart"
formatter = { command = "dart", args = ["format", "--output=show", "--line-length=100"] }
auto-format = true

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
formatter = { command = "rustfmt" }
auto-format = true

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
check.command = "clippy"
cargo.allFeatures = true
procMacro.enable = true

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--parser", "babel"] }
auto-format = true

[[language]]
name = "jsx"
formatter = { command = "prettier", args = ["--parser", "babel"] }
auto-format = true
